<Project><PropertyGroup>
<Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings>
<Version>3.0.1</Version>
<Deterministic>true</Deterministic>
<PathMap>$(MSBuildThisFileDirectory)=/_/</PathMap>
<DebugType>none</DebugType><DebugSymbols>false</DebugSymbols>
<RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
<NuGetAudit>true</NuGetAudit><NuGetAuditMode>all</NuGetAuditMode>
<RestorePackagesPath>$(MSBuildThisFileDirectory).packages</RestorePackagesPath>
</PropertyGroup></Project>
